// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctoTeste.Data;

namespace OctoTeste.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210520065407_InitialSeed")]
    partial class InitialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OctoTeste.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataNascimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoEndereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60dab023-cd94-4f1c-9494-cbea49a9ac93"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e51d378d-38be-4e80-bf18-248073dd057e"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("648d3e4e-3743-432b-8df2-d73f2f0010c1"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("c080b7ef-d06d-4919-837c-5ea09c5dd6f9"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("65af0f71-f833-42ad-9b51-ffdffe8802cc"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("65ea3300-f6cd-4aa5-b6ba-3cd9406fd544"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("0618ca70-e1bd-4a48-9674-c0073041d482"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("5b4b7fa2-7ecf-4329-a4a0-9c9ed616adba"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("04cb7e46-3b58-43f6-9891-69becb9de08c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("43ce4ba1-8968-44a6-bfe8-8a88d19ebd15"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d89338d7-3cac-4a64-b6f6-a624185ed3c1"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b71ce95b-dcbf-46d2-9cde-7533a9a7bf8b"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("a53d0bd6-cb0c-423a-bbee-afad6632d66d"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d941d382-8079-477a-86c1-7a80afbf0ddd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("8a5ad4aa-0557-4331-9dbe-9ed308d97ac4"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("226394b5-d71b-4585-85b0-626fb9e98c28"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("869d0a3f-37dd-4a2e-907c-f149633eece8"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b6086964-cf0d-4700-ba64-787bfffdfa30"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("105a9986-8a02-46d2-bc30-1157f746df6d"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("79840674-bc1a-43ec-9796-cf5534851b4c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("bd24f1c6-9137-4af4-b061-83d7abb11333"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("136412fa-f031-4da2-a8f4-95b13b992b95"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("f5fad52a-8654-4fd3-bd9a-a397fbfd7d7c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("a05b6f83-d756-49ae-83e1-0bbc9acb38e3"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("059bd883-60c7-4030-b027-eba4b4ba4f66"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("69b0bf9f-1142-43e3-9e22-79b1b3a80be8"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e5244be0-2d32-4c86-8a5d-4eb7d5d5303c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("915949af-cb91-49f9-affb-c7381c8a9b67"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("fdbd8d55-0937-437c-8929-e2c22de425c9"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("5f7c252f-361d-4323-a16d-d834392a8336"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("13d786b3-2b7c-4bb3-a2c1-a96950e7f438"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("6627f7ba-7272-4fdd-9151-e3498fefbe08"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b50a9717-4467-4834-849a-069fca17227a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e2a068b4-d737-49f0-ad50-9d5d80876949"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("8409b947-45f5-4b42-9d92-3fc8825252b6"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("6719ae21-0d8b-4471-ab78-fb934739e9ec"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("5fa7a9af-e98f-4f55-bf3c-b560cf099c0c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("3840e792-a06e-46a7-a508-9256770d96de"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("05a2b9f9-548e-4568-b6f9-7213eca65f6d"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("98cd273d-9ab2-4bbf-a181-1eb2f4f5c92c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e7e3aa47-74d7-4647-9af4-703473978222"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b64565cc-622d-47bf-95c3-a943ab36b682"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("6ef79089-e4ba-49be-a21d-9ca857113aa9"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("be994dc0-f8f0-4d50-9e9d-f386d43bdf28"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("dfa22849-aa89-4489-96cd-76e7847c71c3"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("0b070c10-85d8-42e3-ac20-73f31bdea9f1"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d1af9b41-edb2-4e36-86ad-e917a2df83ae"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b1b4ac51-9242-4626-af79-8543995b8583"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("4889865e-8495-4744-b0a7-7089da4c7fcd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("09ed0a5c-c864-407f-8a97-cf785c743c05"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1b4d7197-7f18-4a2a-8cc8-319db764ca43"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ebcf0934-e9d1-4245-849e-d03bae4d12ea"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d5721dff-d2d7-4d63-becb-c7346a6985d8"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b3f56188-0e37-4320-8564-e7e32aa9e170"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("87f5d0a6-3c87-4790-b6a8-31da9e971741"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("3157e2c5-a180-4d94-a8b3-6578930f0edb"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b640cc5f-2073-49e2-a51d-ed8e577f7a81"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("f69077fd-76d8-4524-ad00-eeace6ef7cbf"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("400da8db-e06a-46fe-844b-350854f154c4"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("cc665f4e-876e-4942-9c15-876b372fc004"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("0b00db0b-0a99-4641-a309-79f7104c0b90"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("979ff656-4597-4f65-95b0-019d2fcaeaa7"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("643f9c93-fb87-49bb-9359-4cce2b6812e8"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("7370b3f5-2122-410a-914a-7843f9cef7c2"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("c1de88f5-ebcc-4b6a-96cb-9c4227e48321"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d8727424-3ecc-4f2d-b4ba-9c41ffb44b17"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("2a4f399f-5eef-4aee-8786-da83443be27c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("3d9b2151-9213-489c-85be-62cac8186501"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("79ed0424-a9ce-4aee-9c5e-cbe396d2adee"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("70fc4c9a-0ef2-4330-90fa-514056be55d8"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("2b229819-1c1a-43b6-90aa-6eb1be4fef4a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1453dfa6-ccf2-4a3f-863e-02b9e72a8608"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
