// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctoTeste.Data;

namespace OctoTeste.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210520065652_UpdatedSeed")]
    partial class UpdatedSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OctoTeste.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataNascimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoEndereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce7ec4a9-279b-420b-9daf-b55305b23879"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("76606839-80cc-4963-936b-e203f8dfc873"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("352f1c86-a780-430a-b28f-042279d2d407"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("42bca22e-1793-47b2-916f-e79ec448c4fd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1a4d3cd0-3ac1-4c10-bf43-4eaa6054f9fd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("6ffdbbe4-be3e-4df0-a3b1-29e679fe4424"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d155e68e-a098-4702-8d62-c2fa1ffc2c63"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("881f6fe9-ac9c-48e3-8a0d-c6a9d3a30651"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("f099ec26-f774-44f1-975a-1a064afaaa50"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ba058ff6-319a-4660-b0c4-848fb9f7e484"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("96992f0d-00f7-444a-92ab-6de072eb4d28"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("eaa7422c-3f5b-4ec3-94f6-bbae750e6e60"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("6243af86-c585-436c-97f8-e8fd56ac12ec"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("5a1ffc04-eccf-44eb-9bb7-6dc29510ff84"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("0b51ed01-64c8-428d-bb6e-ec1fbd01226f"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e5ae12ab-b556-4a5b-b57a-19bbdb5b7614"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("095e6335-173b-473a-8179-0fbf7c72571c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("f195d2f9-d66e-4a00-bfdc-5dc70fad4ebe"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ec4588d3-b28c-4acc-a115-868818bc308a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("5b43322c-28db-4d8c-8889-316d0f8b94dd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("052115b4-a665-4bc5-8660-e98f9e5c2402"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("bfb622ef-911d-498e-bb70-f313f92a5b56"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ad021735-209d-40ed-b63b-1f2f15738559"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e9c4843c-fa10-4c02-add2-63739c77281a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("304fabdc-86da-47fe-812c-8e29f372549b"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ead9a125-e8a2-4eb9-bed2-4700d38a0199"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("530a191e-f987-4153-83cf-80ca4ca0de34"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d7f34edb-b166-4676-8c05-b9ed98083a60"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("c50990b2-7d70-4d38-9341-030fd00080d5"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("cff7ae5b-4c6a-4ae4-8989-cd676a50705f"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("731f84e0-fc1d-4b1a-82ba-da00f402e53c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("63a9cc22-857a-40af-ba25-7fce80165bd1"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("6fa1044f-125d-45ae-9a40-f4d1ad9e26f4"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("90765216-9ff7-4be9-864c-036fcb0df587"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b4703499-515e-429a-98f2-2c19202c4203"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("0fee431c-08d0-4231-926c-21600770ebfe"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("0376bfd2-c3b9-4f42-b216-1281e40f5d6a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("db3ed997-8961-4811-9ef0-c7264ad5e51b"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("50067aa2-bc3d-4986-b904-06d53c04e435"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("97fa1c24-aece-47b9-9fc4-520962abff9d"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("11fd5511-b9af-4fe5-9c44-e74dbb75872b"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("84c5cefc-d5a4-421b-8364-f442a2315b37"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("025e0af5-3b71-42c7-b284-685af5178c7c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("9193e2c5-f4a4-470b-878e-c4bffe6e1761"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b9a34abc-f4b8-4a0a-abb5-6fb92085c72a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ee071dc6-3817-4640-afe8-1addc1a08809"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("2fe6913c-d377-4ef1-aad9-0f6ff279bd26"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("f43a1748-1cf5-4eb8-9d71-4d3fb44778b2"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("880d51f3-0cf5-4cda-ad1a-d2c508df019d"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("00bb75d6-953b-4b62-92d3-b0a3d880bdc0"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("41e18fb7-e3d5-45a5-9c87-a4a191c64f74"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ade4d1ea-bd40-45da-bdae-409e1c1733a8"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("051ac0ee-72fe-4868-8e24-69cbad0fdb32"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("eb37f1af-0169-417c-ba60-184fea3ea895"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("8f12b3e9-35cf-4846-a6da-01373d6610d6"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b946219b-4a24-4780-a63c-4ff196aef378"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e86b39d9-e332-4998-82ed-5cd6e0f3ef3d"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("cbfb3463-7074-480f-8154-beac2299d04f"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("25a6fa6c-8531-42ec-97bc-96e73d385b26"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("baf2ab0c-334f-4855-b808-7428bcb2a3cd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("cd3c530b-8eef-4abb-8ead-cd697a5cefcd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("2a9bacc8-934d-43ae-b6a1-44a20dbbc7ab"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ee052a5f-182c-43d2-a173-e5e86d6d6dd3"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d033e057-469e-4413-a223-f35978e6c94b"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("bf877146-9ae9-4430-9b12-771f6f85e9f5"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("b4451fd2-5594-462c-aaa1-3eece0cf90f4"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1a9ea688-8bc5-416e-ad1b-63f25e7f50d3"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("2f4d52b2-9647-4b86-9f98-a1b88fe03908"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("f7f6068d-0896-4d6a-8a0f-0f834002d677"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("056a0291-04f7-4706-95db-33368063cf1f"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("551fe363-fb67-4dd3-b9b8-d0061a2dc68e"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("dfd37cf0-627a-437b-aa3d-224a3309ec58"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("366293bd-e779-4cda-8213-59dff6adf2d4"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("c776e09e-62c5-4020-a1d3-4d3ff145660a"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("e2f5ae2e-dd2f-4729-9287-4858cfe2462c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("202b6504-fcf8-4416-8f92-85e19db6c662"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("5e05e862-d435-468c-9749-f31614490b4e"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("d5a0b04a-7131-4dd5-9058-21c9159263d1"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ae6d218e-e06d-4bc7-a76f-8e078207545b"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("429f5266-c525-4829-88b2-b23bd7189a4e"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("60f967b9-8d74-4971-81dc-3ab5d65fe23c"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("cfa69bf6-85b2-4624-90a5-216db6a317dd"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("16269c53-34cb-46c2-af8c-bfaa52307efe"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        },
                        new
                        {
                            Id = new Guid("35b8106f-22a3-41c9-97bc-74575d9caff6"),
                            Cep = "29031-843",
                            Cpf = "371.920.561-46",
                            Endereco = "Rua Dezessete de Dezembro",
                            Nome = "Renato",
                            Numero = 872,
                            Telefone = "(27) 99345-4790",
                            dataNascimento = "08/03/1995",
                            tipoEndereco = "Cobrança",
                            tipoTelefone = "Celular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
